In [1]:
import glob
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm


from PIL import Image

import nltk

font_name = fm.FontProperties(fname='C:/windows/Fonts/malgun.ttf').get_name()
plt.rc('font',family =font_name)
mpl.rcParams['axes.unicode_minus'] = False
%matplotlib inline

In [2]:
file_list = [] #재귀 탐색
for filename in glob.iglob('./**/*info.csv', recursive=True):
    file_list.append(filename)
    print(filename)
    
print("-------------")
print(file_list)

.\Hyojin\Hyojin_info.csv
.\Joan Kim\Joan Kim_info.csv
.\lamuqe\lamuqe_info.csv
.\PONY Syndrome\PONY Syndrome_info.csv
.\RISABAE\RISABAE_info.csv
.\Sunny_s\Sunny_s_info.csv
.\개코의 오픈스튜디오\개코의 오픈스튜디오_info.csv
.\기우쌤\기우쌤_info.csv
.\다또아\다또아_info.csv
.\다영\다영_info.csv
.\도영이\도영이_info.csv
.\디렉터파이\디렉터파이_info.csv
.\디어제리\디어제리_info.csv
.\로즈하\로즈하_info.csv
.\리안\리안_info.csv
.\새벽\새벽_info.csv
.\샒의 삶\샒의 삶_info.csv
.\소윤\소윤_info.csv
.\슈스스\슈스스_info.csv
.\씬님\씬님_info.csv
.\아름송이\아름송이_info.csv
.\연두콩\연두콩_info.csv
.\유나\유나_info.csv
.\윤짜미\윤짜미_info.csv
.\젤라\젤라_info.csv
.\한별\한별_info.csv
.\헤이즐\헤이즐_info.csv
.\홀리\홀리_info.csv
.\회사원A\회사원A_info.csv
.\희주\희주_info.csv
-------------
['.\\Hyojin\\Hyojin_info.csv', '.\\Joan Kim\\Joan Kim_info.csv', '.\\lamuqe\\lamuqe_info.csv', '.\\PONY Syndrome\\PONY Syndrome_info.csv', '.\\RISABAE\\RISABAE_info.csv', '.\\Sunny_s\\Sunny_s_info.csv', '.\\개코의 오픈스튜디오\\개코의 오픈스튜디오_info.csv', '.\\기우쌤\\기우쌤_info.csv', '.\\다또아\\다또아_info.csv', '.\\다영\\다영_info.csv', '.\\도영이\\도영이_info.csv', '.\\디렉터파이\\디렉터파이_info.csv', '.\\디어제리\\디어제리_info.csv', '.\\로즈하\\로즈하_info.csv', '.\\리안\\리안_info.csv', '.\\새벽\\새벽_info.csv', '.\\샒의 삶\\샒의 삶_info.csv', '.\\소윤\\소윤_info.csv', '.\\슈스스\\슈스스_info.csv', '.\\씬님\\씬님_info.csv', '.\\아름송이\\아름송이_info.csv', '.\\연두콩\\연두콩_info.csv', '.\\유나\\유나_info.csv', '.\\윤짜미\\윤짜미_info.csv', '.\\젤라\\젤라_info.csv', '.\\한별\\한별_info.csv', '.\\헤이즐\\헤이즐_info.csv', '.\\홀리\\홀리_info.csv', '.\\회사원A\\회사원A_info.csv', '.\\희주\\희주_info.csv']

In [3]:
view_sum = []
view_mean = []
comment_sum = []
comment_mean = []
like_sum = []
like_mean = []
unlike_sum = []
unlike_mean = []
duration_sum = []
duration_mean =[]
youtube_name = []
subscriber = []

In [4]:
for i in file_list:
#     print(i[0:-9])
    print(i.split('\\')[1])
    youtube_name.append(i.split('\\')[1])
    
youtube_name

Hyojin
Joan Kim
lamuqe
PONY Syndrome
RISABAE
Sunny_s
개코의 오픈스튜디오
기우쌤
다또아
다영
도영이
디렉터파이
디어제리
로즈하
리안
새벽
샒의 삶
소윤
슈스스
씬님
아름송이
연두콩
유나
윤짜미
젤라
한별
헤이즐
홀리
회사원A
희주

['Hyojin',
 'Joan Kim',
 'lamuqe',
 'PONY Syndrome',
 'RISABAE',
 'Sunny_s',
 '개코의 오픈스튜디오',
 '기우쌤',
 '다또아',
 '다영',
 '도영이',
 '디렉터파이',
 '디어제리',
 '로즈하',
 '리안',
 '새벽',
 '샒의 삶',
 '소윤',
 '슈스스',
 '씬님',
 '아름송이',
 '연두콩',
 '유나',
 '윤짜미',
 '젤라',
 '한별',
 '헤이즐',
 '홀리',
 '회사원A',
 '희주']

In [ ]:
# youtube = pd.read_csv(file_list[8],index_col= 'name')
# youtube

In [5]:
for i in file_list:
#     youtube = pd.read_csv(i,index_col= 'name')
    youtube = pd.read_csv(i,index_col= 'name')
    youtube
    youtube.columns
#youtube = youtube.loc[youtube['view'].str.contains('만회',na=False)]

    views = []
    for i in youtube['view']:
        if '만회' in i :
            views.append(float(i.split('만회')[0])*10000)
        elif '천회' in i:
            views.append(float(i.split('천회')[0])*1000)
        elif '회' in i :
            views.append(float(i.split('회')[0]))
        
    youtube['조회수']= views

    youtube['조회수'].astype('int')
    youtube['조회수']= youtube['조회수'].astype('int')

    comment1=[]
    for i in youtube['comment']:
        i = (i.split(' ')[1].split('개')[0])
        if ',' in i:
            i = i.split(',')[0]+i.split(',')[1]
    
        comment1.append(int(i))    
    

    youtube['댓글수']= comment1

    like =[]
    for i in youtube['likes_num']:
        if '만개' in i :
            like.append(float(i.split('만개')[0])*10000)
        elif '천개' in i:
            like.append(float(i.split('천개')[0])*1000)
        elif '개' in i :
            like.append(float(i.split('개')[0]))
    
    like
    youtube['좋아요수'] = like
    youtube['좋아요수'] = youtube['좋아요수'].astype('int')

    unlike =[]
    for i in youtube['unlikes_num']:
        if '만개' in i :
            unlike.append(float(i.split('만개')[0])*10000)
        elif '천개' in i:
            unlike.append(float(i.split('천개')[0])*1000)
        elif '개' in i :
            unlike.append(float(i.split('개')[0]))
    
    unlike
    youtube['싫어요수']=unlike
    youtube['싫어요수']=youtube['싫어요수']

    time = []
    for i in youtube['time_duration']:
        a=int(i.split('\n')[1].split(':')[0])
        b= int(i.split('\n')[1].split(':')[1])
        time.append((60*a)+b)
    youtube['영상길이']= time

    del youtube['time_duration']
    del youtube['video_url']
    del youtube['thumbnail']
    del youtube['Unnamed: 0']
    del youtube['view']
    del youtube['previous_time']
    del youtube['start_date']
    del youtube['comment']
    del youtube['likes_num']
    del youtube['unlikes_num']
#     youtube

    comment_sum.append(youtube['댓글수'].sum())
    view_sum.append(youtube['조회수'].sum())
    like_sum.append(youtube['좋아요수'].sum())
    duration_sum.append(youtube['영상길이'].sum())
    unlike_sum.append(youtube['싫어요수'].sum())
    comment_mean.append(round(youtube['댓글수'].mean(),2))
    view_mean.append(round(youtube['조회수'].mean(),2))
    like_mean.append(round(youtube['좋아요수'].mean(),2))
    duration_mean.append(round(youtube['영상길이'].mean(),2))
    unlike_mean.append(round(youtube['싫어요수'].mean(),2))
# comment_sum

In [8]:
collection = pd.DataFrame({'유투버':youtube_name,
                           '조회수합':view_sum,
                          '조회수평균':view_mean,
                          '댓글수합':comment_sum,
                          '댓글수평균':comment_mean,
                          '좋아요합':like_sum,
                          '좋아요평균':like_mean,
                          '싫어요합':unlike_sum,
                          '싫어요평균':unlike_mean,
                          '영상길이합':duration_sum,
                          '영상길이평균':duration_mean})
collection.to_csv('./Total_Result.csv',encoding= 'utf-8-sig')
collection

,유투버,조회수합,조회수평균,댓글수합,댓글수평균,좋아요합,좋아요평균,싫어요합,싫어요평균,영상길이합,영상길이평균
0,Hyojin,5709000,285450.00,10084,504.20,122600,6130.00,1736.0,86.80,26018,1300.90
1,Joan Kim,2137000,106850.00,6218,310.90,72300,3615.00,1691.0,84.55,19858,992.90
2,lamuqe,2821000,141050.00,4915,245.75,50527,2526.35,1064.0,53.20,19719,985.95
3,PONY Syndrome,12506000,625300.00,11378,568.90,491000,24550.00,5350.0,267.50,13886,694.30
4,RISABAE,5209000,260450.00,8587,429.35,112300,5615.00,1468.0,73.40,14568,728.40
5,Sunny_s,3420000,171000.00,6177,308.85,87400,4370.00,1004.0,50.20,22221,1111.05
6,개코의 오픈스튜디오,2987000,426714.29,5191,741.57,85200,12171.43,1196.0,170.86,3867,552.43
7,기우쌤,2137000,106850.00,6218,310.90,72300,3615.00,1691.0,84.55,19858,992.90
8,다또아,2658000,132900.00,7015,350.75,50904,2545.20,2558.0,127.90,17238,861.90
9,다영,1968000,98400.00,6165,308.25,37200,1860.00,978.0,48.90,25417,1270.85
10,도영이,5940000,297000.00,9347,467.35,227500,11375.00,1248.0,62.40,13947,697.35
11,디렉터파이,2187000,198818.18,4202,382.00,39866,3624.18,751.0,68.27,12965,1178.64
12,디어제리,2921000,146050.00,4470,223.50,68600,3430.00,1272.0,63.60,22332,1116.60
13,로즈하,2345000,213181.82,42581,3871.00,77000,7000.00,1186.0,107.82,11491,1044.64
14,리안,2347000,117350.00,3519,175.95,55100,2755.00,810.0,40.50,15433,771.65
15,새벽,2500000,125000.00,4442,222.10,45557,2277.85,1268.0,63.40,20109,1005.45
16,샒의 삶,4900000,245000.00,11257,562.85,114300,5715.00,1769.0,88.45,31186,1559.30
17,소윤,3640000,182000.00,6655,332.75,71400,3570.00,1427.0,71.35,32553,1627.65
18,슈스스,5907000,295350.00,11099,554.95,132800,6640.00,2577.0,128.85,15188,759.40
19,씬님,6112000,305600.00,9128,456.40,106400,5320.00,1609.0,80.45,23239,1161.95
20,아름송이,4195000,209750.00,5484,274.20,78300,3915.00,1372.0,68.60,22512,1125.60
21,연두콩,1797000,119800.00,8613,574.20,44300,2953.33,585.0,39.00,8956,597.07
22,유나,1297000,108083.33,4222,351.83,24254,2021.17,845.0,70.42,9019,751.58
23,윤짜미,6140000,307000.00,21839,1091.95,141600,7080.00,3348.0,167.40,16618,830.90
24,젤라,2150000,143333.33,4692,312.80,58900,3926.67,1110.0,74.00,15772,1051.47
25,한별,1720000,172000.00,4098,409.80,33800,3380.00,991.0,99.10,9236,923.60
26,헤이즐,3840000,192000.00,8340,417.00,57400,2870.00,2175.0,108.75,21740,1087.00
27,홀리,3486000,174300.00,4840,242.00,74000,3700.00,1100.0,55.00,22625,1131.25
28,회사원A,6014000,300700.00,16171,808.55,93155,4657.75,4351.0,217.55,18198,909.90
29,희주,1837000,122466.67,6803,453.53,84300,5620.00,803.0,53.53,11506,767.07