In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm            # 폰트 지정방법
font_name=fm.FontProperties(fname='C:\\Windows\\Fonts\\malgun.ttf').get_name()     
plt.rc('font',family=font_name)


mpl.rcParams['axes.unicode_minus']=False

In [2]:
import glob

In [6]:
view_sum = []
view_mean = []
comment_sum = []
comment_mean = []
like_sum= []
like_mean = []
unlike_sum = []
unlike_mean = []
duration_sum =[]
duration_mean = []
youtube_name = []

['백종원', '떵개떵', '문복희', '하루한끼', '햄지', '쿠킹트리', 'FRAN', '쯔양', '유디티', '한세', '푸메', '꿀키', 'MINEE EATS', '엠브로', '나름', '아리키친', '애주가', 'SOF', '입짧은햇님', '상윤쓰', '야식이', '산적TV', '아내의식탁', '권회훈', '수빙수', '먹어볼래', '신쿡', '가르마', '시니', '맛상무']

In [7]:
collection = pd.DataFrame({
    "유투버":youtube_name,
    '조회수합' : view_sum,
    '조회수평균' : view_mean,

    '댓글수합' : comment_sum,
    '댓글수평균' :comment_mean,

    '좋아요합' :like_sum,
    '좋아요평균' :like_mean,

    '싫어요합' : unlike_sum,
    '싫어요평균' : unlike_mean,

    '영상길이합' : duration_sum,
    '영상길이평균' : duration_mean
})
collection

Empty DataFrame
Columns: [유투버, 조회수합, 조회수평균, 댓글수합, 댓글수평균, 좋아요합, 좋아요평균, 싫어요합, 싫어요평균, 영상길이합, 영상길이평균]
Index: []

In [8]:
path = "./*"
file_list = glob.glob(path)
file_list_py = [file for file in file_list if file.endswith(".csv")]

In [9]:
file_list_py
youtube_name = []
for i in file_list_py:
    youtube_name.append(i.split('\\')[1].split('.')[1].split('_')[0])
print(youtube_name)

['백종원', '떵개떵', '문복희', '하루한끼', '햄지', '쿠킹트리', 'FRAN', '쯔양', '유디티', '한세', '푸메', '꿀키', 'MINEE EATS', '엠브로', '나름', '아리키친', '애주가', 'SOF', '입짧은햇님', '상윤쓰', '야식이', '산적TV', '아내의식탁', '권회훈', '수빙수', '먹어볼래', '신쿡', '가르마', '시니', '맛상무']

In [11]:
collection['유투버'] = youtube_name
collection

,유투버,조회수합,조회수평균,댓글수합,댓글수평균,좋아요합,좋아요평균,싫어요합,싫어요평균,영상길이합,영상길이평균
0,백종원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,떵개떵,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,문복희,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,하루한끼,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,햄지,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,쿠킹트리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,FRAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,쯔양,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,유디티,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,한세,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,푸메,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,꿀키,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,MINEE EATS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,엠브로,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,나름,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,아리키친,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,애주가,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,SOF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,입짧은햇님,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,상윤쓰,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,야식이,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,산적TV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,아내의식탁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,권회훈,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,수빙수,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,먹어볼래,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,신쿡,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,가르마,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,시니,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,맛상무,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i in file_list:
    #print(i)
    #print(type(i)) 
    youtube=pd.read_csv(i)
    #youtube=pd.read_csv(i,encoding= 'unicode_escape')
    print(youtube)
#print(type(youtube))

In [ ]:
y_name = input('유튜브명 : ')
dddd = pd.read_csv(y_name+'_info.csv',encoding='euc-kr')
dddd

In [ ]:
dddd.to_csv('./'+y_name+'_info.csv',encoding='utf-8-sig')

In [ ]:

for i in range(len(file_list)):
    #print(i)
    #print(type(i)) 
    youtube=pd.read_csv(i)
    
    
    
    #조회수 '만회'제거하고 정수형태로 바꾸기
    view1 = []
    for i in youtube['view'].values:
        tmp=i.split("만회")[0]
        tmp2=int(tmp)
        view1.append(tmp2*10000)

        youtube['view']=view1


    # 댓글개수
    comment1=[]
    for i in youtube['comment']:
        i = (i.split(' ')[1].split('개')[0])
        if ',' in i:
            i = i.split(',')[0]+i.split(',')[1]
    
        comment1.append(int(i))    
    
    youtube['comment']=comment1


    # 좋아요개수
    like1=[]
    for i in youtube['likes_num']:
        if '천개' in i:
            a=float(i.split('천개')[0])*1000
            like1.append(int(a))
            
        else :
            b=float(i.split('만개')[0])*10000
            like1.append(int(b))

    youtube['likes_num']=like1



    # 싫어요 개수
    unlike1=[]
    for i in youtube['unlikes_num'].values:
        unlike_tmp=int(i.split('개')[0])
        unlike1.append(unlike_tmp)
        #print(unlike_tmp)
    youtube['unlikes_num']=unlike1
  
    
    
    # 영상길이
    time = []
    for i in youtube['time_duration']:
        a=int(i.split('\n')[1].split(':')[0])
        b= int(i.split('\n')[1].split(':')[1])
        time.append((60*a)+b)
    youtube['time_duration']= time
    
    
    
    collection['조회수합'][]=




#     sum_avg = {
#          '조회수합' : youtube['view'].sum(axis=0),
#          '조회수평균' : youtube['view'].mean(),

#          '댓글수합' : youtube['comment'].sum(axis=0),
#          '댓글수평균' : youtube['comment'].mean(),

#          '좋아요합' : youtube['likes_num'].sum(axis=0),
#          '좋아요평균' : youtube['likes_num'].mean(),

#          '싫어요합' : youtube['unlikes_num'].sum(axis=0),
#          '싫어요평균' : youtube['unlikes_num'].mean(),

#          '영상길이합' : youtube['time_duration'].sum(axis=0),
#          '영상길이평균' : youtube['time_duration'].mean()
#     }


idx=['백종원','떵개떵','문복희','하루한끼','햄지','쿠킹트리','FRAN','쯔양','유디티','한세',
    '푸메','꿀키','MINEE EATS','엠브로','나름','아리키친','애주가','SOF','입짧은햇님','상윤쓰',
    '야식이','산적TV','아내의식탁','권회훈','수빙수','먹어볼래','신쿡','가르마','시니','맛상무']    

youtube2=pd.DataFrame(sum_avg,index=idx)

youtube2

In [ ]:
sum_avg

In [ ]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df.loc['제주도'] =['수도권','22','33','44','55','11']
df.loc['유투버이름'] = ['youtube['view'].sum(axis=0)',' youtube['view'].mean()',]
df['유투버이름'] = youtube

In [17]:
list1=[1,2,3,4,5]
list2=[1,2,2,2,2]
list3=[3,3,3,3,3]

a = 3
for i in range(30):

'내가 원하는정보'